# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .bing_commerce_ingestion import BingCommerceIngestion
from .version import VERSION

__all__ = ['BingCommerceIngestion']

__version__ = VERSION

