# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class GeoPoint(Model):
    """Defines a geo-location based on lattitude and longitude.

    :param lat: The lattitude of the location.
    :type lat: float
    :param lon: The longitude of the location.
    :type lon: float
    """

    _attribute_map = {
        'lat': {'key': 'lat', 'type': 'float'},
        'lon': {'key': 'lon', 'type': 'float'},
    }

    def __init__(self, *, lat: float=None, lon: float=None, **kwargs) -> None:
        super(GeoPoint, self).__init__(**kwargs)
        self.lat = lat
        self.lon = lon
