# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class RequestClient(Model):
    """RequestClient.

    :param ids:
    :type ids: list[~microsoft.bing.commerce.search.models.RequestClientId]
    """

    _attribute_map = {
        'ids': {'key': 'ids', 'type': '[RequestClientId]'},
    }

    def __init__(self, *, ids=None, **kwargs) -> None:
        super(RequestClient, self).__init__(**kwargs)
        self.ids = ids
