# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class RequestClientId(Model):
    """RequestClientId.

    :param kind: Possible values include: 'MUID', 'UID'. Default value: "MUID"
     .
    :type kind: str or ~microsoft.bing.commerce.search.models.enum
    :param value:
    :type value: str
    """

    _attribute_map = {
        'kind': {'key': 'kind', 'type': 'str'},
        'value': {'key': 'value', 'type': 'str'},
    }

    def __init__(self, *, kind="MUID", value: str=None, **kwargs) -> None:
        super(RequestClientId, self).__init__(**kwargs)
        self.kind = kind
        self.value = value
