# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .request_query_clause_base_py3 import RequestQueryClauseBase


class RequestQueryClauseBlock(RequestQueryClauseBase):
    """Defines a list of QueryClauseBase objects that should all match. Nested
    QueryClauseBlock within QueryClauseBlock is not allowed.

    All required parameters must be populated in order to send to Azure.

    :param _type: Required. Constant filled by server.
    :type _type: str
    :param values: A list of queryclausebase conditions to be applied.
    :type values:
     list[~microsoft.bing.commerce.search.models.RequestQueryClauseBase]
    """

    _validation = {
        '_type': {'required': True},
    }

    _attribute_map = {
        '_type': {'key': '_type', 'type': 'str'},
        'values': {'key': 'values', 'type': '[RequestQueryClauseBase]'},
    }

    def __init__(self, *, values=None, **kwargs) -> None:
        super(RequestQueryClauseBlock, self).__init__(**kwargs)
        self.values = values
        self._type = 'QueryClauseBlock'
