# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ResponseBingMatchingStream(Model):
    """ResponseBingMatchingStream.

    :param name:
    :type name: str
    :param score:
    :type score: int
    """

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'score': {'key': 'score', 'type': 'int'},
    }

    def __init__(self, *, name: str=None, score: int=None, **kwargs) -> None:
        super(ResponseBingMatchingStream, self).__init__(**kwargs)
        self.name = name
        self.score = score
