# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .response_debug_info import ResponseDebugInfo


class ResponseBingBingItemDebugInfo(ResponseDebugInfo):
    """ResponseBingBingItemDebugInfo.

    All required parameters must be populated in order to send to Azure.

    :param _type: Required. Constant filled by server.
    :type _type: str
    :param perfect_matching_streams:
    :type perfect_matching_streams:
     list[~microsoft.bing.commerce.search.models.ResponseBingMatchingStream]
    :param complete_matching_streams:
    :type complete_matching_streams:
     list[~microsoft.bing.commerce.search.models.ResponseBingMatchingStream]
    """

    _validation = {
        '_type': {'required': True},
    }

    _attribute_map = {
        '_type': {'key': '_type', 'type': 'str'},
        'perfect_matching_streams': {'key': 'perfectMatchingStreams', 'type': '[ResponseBingMatchingStream]'},
        'complete_matching_streams': {'key': 'completeMatchingStreams', 'type': '[ResponseBingMatchingStream]'},
    }

    def __init__(self, **kwargs):
        super(ResponseBingBingItemDebugInfo, self).__init__(**kwargs)
        self.perfect_matching_streams = kwargs.get('perfect_matching_streams', None)
        self.complete_matching_streams = kwargs.get('complete_matching_streams', None)
        self._type = 'BingItemDebugInfo'
