# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Synonym(Model):
    """Defines a set of alternate terms (or phrases) that can be applied to
    request query.

    :param synonym_id: The id for the saved synonym.
    :type synonym_id: str
    :param synonyms: The alternate terms to apply
    :type synonyms: list[str]
    """

    _attribute_map = {
        'synonym_id': {'key': 'synonymId', 'type': 'str'},
        'synonyms': {'key': 'synonyms', 'type': '[str]'},
    }

    def __init__(self, **kwargs):
        super(Synonym, self).__init__(**kwargs)
        self.synonym_id = kwargs.get('synonym_id', None)
        self.synonyms = kwargs.get('synonyms', None)
