# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class TransformationConfigResponse(Model):
    """TransformationConfigResponse.

    :param value: The contents of the transformation config that's being
     managed.
    :type value: str
    :param try_out_id: An id that you can use to tryout your transformation on
     the cloud.
    :type try_out_id: str
    """

    _attribute_map = {
        'value': {'key': 'value', 'type': 'str'},
        'try_out_id': {'key': 'tryOutId', 'type': 'str'},
    }

    def __init__(self, *, value: str=None, try_out_id: str=None, **kwargs) -> None:
        super(TransformationConfigResponse, self).__init__(**kwargs)
        self.value = value
        self.try_out_id = try_out_id
