# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

try:
    from .requests_string_set_py3 import RequestsStringSet
    from .index_field_py3 import IndexField
    from .index_py3 import Index
    from .response_index_py3 import ResponseIndex
    from .index_response_py3 import IndexResponse
    from .response_document_deletion_result_py3 import ResponseDocumentDeletionResult
    from .delete_documents_response_py3 import DeleteDocumentsResponse
    from .response_index_status_py3 import ResponseIndexStatus
    from .index_status_response_py3 import IndexStatusResponse
    from .push_data_update_response_py3 import PushDataUpdateResponse
    from .response_record_status_py3 import ResponseRecordStatus
    from .push_update_status_response_py3 import PushUpdateStatusResponse
    from .transformation_config_response_py3 import TransformationConfigResponse
    from .transformation_tryout_response_py3 import TransformationTryoutResponse
    from .schema_detection_response_py3 import SchemaDetectionResponse
except (SyntaxError, ImportError):
    from .requests_string_set import RequestsStringSet
    from .index_field import IndexField
    from .index import Index
    from .response_index import ResponseIndex
    from .index_response import IndexResponse
    from .response_document_deletion_result import ResponseDocumentDeletionResult
    from .delete_documents_response import DeleteDocumentsResponse
    from .response_index_status import ResponseIndexStatus
    from .index_status_response import IndexStatusResponse
    from .push_data_update_response import PushDataUpdateResponse
    from .response_record_status import ResponseRecordStatus
    from .push_update_status_response import PushUpdateStatusResponse
    from .transformation_config_response import TransformationConfigResponse
    from .transformation_tryout_response import TransformationTryoutResponse
    from .schema_detection_response import SchemaDetectionResponse
from .bing_commerce_ingestion_enums import (
    ResponsePushStatus,
    Region,
    IndexFieldType,
)

__all__ = [
    'RequestsStringSet',
    'IndexField',
    'Index',
    'ResponseIndex',
    'IndexResponse',
    'ResponseDocumentDeletionResult',
    'DeleteDocumentsResponse',
    'ResponseIndexStatus',
    'IndexStatusResponse',
    'PushDataUpdateResponse',
    'ResponseRecordStatus',
    'PushUpdateStatusResponse',
    'TransformationConfigResponse',
    'TransformationTryoutResponse',
    'SchemaDetectionResponse',
    'ResponsePushStatus',
    'Region',
    'IndexFieldType',
]
