# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class IndexResponse(Model):
    """A response containing a list of indexes.

    :param indexes: A list of indexes
    :type indexes:
     list[~microsoft.bing.commerce.ingestion.models.ResponseIndex]
    """

    _attribute_map = {
        'indexes': {'key': 'indexes', 'type': '[ResponseIndex]'},
    }

    def __init__(self, **kwargs):
        super(IndexResponse, self).__init__(**kwargs)
        self.indexes = kwargs.get('indexes', None)
